---

- name: Delete all repo files
  file:
    path: "/etc/yum.repos.d/{{ item }}"
    state: absent
  with_items:
    - CentOS-Base.repo
    - epel.repo 

- name: Add epel repository gpg key
  rpm_key:
    state: present
    key: https://mirror.tuna.tsinghua.edu.cn/epel/RPM-GPG-KEY-EPEL-7

- name: Add CentOS Base repository geg key
  rpm_key:
    state: present
    key: https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-7

- name: Add epel repository
  yum_repository:
    name: epel
    description: "Extra Packages for Enterprise Linux 7 - $basearch"
    baseurl: https://mirrors.tuna.tsinghua.edu.cn/epel/7/$basearch
    gpgcheck: yes
    enabled: yes
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
    failovermethod: priority

- name: Add CentOS repository
  yum_repository:
    file: CentOS-Base
    name: "{{ item.name }}"
    description: "CentOS-$releasever - {{ item.name }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: yes
    enabled: yes
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    failovermethod: priority
  with_items:
    - { name: 'base', baseurl: 'https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/os/$basearch/' }
    - { name: 'updates', baseurl: 'https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/updates/$basearch/' }
    - { name: 'extras', baseurl: 'https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/extras/$basearch/' }